=== maargin/yohaku-challenge7/schema/policy.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "policy.json",
  "type": "object",
  "required": ["arch", "activation", "obs_mean", "obs_std", "layers", "actions"],
  "properties": {
    "arch": {"type": "array", "minItems": 2, "maxItems": 6, "items": {"type": "integer", "minimum": 1, "maximum": 1024}},
    "activation": {"enum": ["tanh", "relu"]},
    "obs_mean": {"type": "array", "items": {"type": "number"}},
    "obs_std": {"type": "array", "items": {"type": "number", "exclusiveMinimum": 0}},
    "layers": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["W", "b"],
        "properties": {
          "W": {"type": "array", "items": {"type": "array", "items": {"type": "number"}}},
          "b": {"type": "array", "items": {"type": "number"}}
        },
        "additionalProperties": false
      }
    },
    "actions": {"type": "array", "minItems": 7, "maxItems": 7, "items": {"type": "string", "maxLength": 32}}
  },
  "additionalProperties": false
}

=== maargin/yohaku-challenge7/web/data/policy.json
{"actions":["hold","small_open","large_open","small_close","radial","request_yield","escalate"],"activation":"tanh","arch":[24,64,64,7],"layers":[{"W":[[-0.3181670010089874,-0.09089428931474686,-0.17104803025722504,-0.1420559138059616,-0.16376684606075287,-0.21993961930274963,0.09756074100732803,0.1253993660211563,0.011139907874166965,0.08810585737228394,-0.04952379688620567,0.06601452827453613,-0.030398735776543617,0.06610459834337234,-0.07787884771823883,-0.054446808993816376,-0.0019773803651332855,0.04635639116168022,-0.03338906913995743,0.23747767508029938,0.31474435329437256,0.5291271209716797,0.6340233683586121,-0.03529633209109306],[-0.7715908885002136,0.138998344540596,-0.10274087637662888,0.5015132427215576,-0.21251508593559265,-0.5466558933258057,0.01601959951221943,0.004934411030262709,-0.06166347116231918,-0.03315327689051628,-0.015974950045347214,-0.1103227511048317,-0.05799121782183647,-0.08543102443218231,-0.049579910933971405,-0.03688935562968254,0.005068054422736168,-0.06768404692411423,0.2703842222690582,0.06731188297271729,-0.09975102543830872,0.04511723667383194,-0.28016719222068787,0.03566873446106911],[-0.07084140926599503,0.03933257982134819,0.011470489203929901,-0.0871061235666275,0.03858249634504318,0.3413238525390625,0.08215412497520447,0.09724865108728409,-0.032792747020721436,0.0755428671836853,0.07852297276258469,-0.040468163788318634,0.10986886918544769,-0.031407784670591354,-0.05155753716826439,-0.027002643793821335,-0.12514860928058624,-0.11741659790277481,-0.117216095328331,0.11979026347398758,0.3103935122489929,-0.12807033956050873,0.33522310853004456,0.18308158218860626],[-0.0757649764418602,-0.04377555102109909,0.101870596408844,-0.1148630753159523,0.07579763978719711,0.4022539556026459,0.18199758231639862,0.03479912877082825,-0.2213117629289627,-0.09759029746055603,-0.14823731780052185,0.19248120486736298,-0.008923693560063839,0.00997710507363081,-0.06632158160209656,-0.06659959256649017,-0.15278732776641846,-0.05037369206547737,0.08663253486156464,-0.10150670260190964,-0.3906444311141968,0.2547357678413391,-0.4268878996372223,0.07078079879283905],[-0.0317668654024601,0.11459210515022278,-0.07122102379798889,-0.08815160393714905,-0.03259260952472687,0.09416612237691879,-0.01408229861408472,-0.01801232434809208,-0.010761379264295101,-0.03582020848989487,-0.04486140236258507,-0.11492431163787842,0.07203271239995956,-0.09598954021930695,0.11035291105508804,0.05042588338255882,-0.15180662274360657,-0.21294112503528595,-0.15006789565086365,-0.13576862215995789,0.2198026180267334,0.8623748421669006,0.03235906362533569,-0.022913509979844093],[0.11202432215213776,-0.15368114411830902,-0.14395122230052948,-0.11027412116527557,-0.14901669323444366,-0.10459044575691223,0.03034970536828041,-0.0030545461922883987,-0.006857393309473991,-0.005695087369531393,0.03008340857923031,-0.04683980718255043,0.042483411729335785,-0.014724434353411198,-0.09662777185440063,-0.002472164109349251,0.10149107873439789,0.07071801275014877,-0.19345374405384064,-0.10300850868225098,-0.6296822428703308,0.42950505018234253,-0.38314560055732727,0.03753037750720978],[0.5166289806365967,-0.03215407207608223,-0.04378904774785042,-0.215885192155838,0.08329658955335617,0.5170024037361145,0.010423101484775543,0.03865189105272293,0.06365314871072769,0.05692104622721672,0.04751884192228317,-0.02278353087604046,0.0539872869849205,0.006255543790757656,-0.024979950860142708,-0.0009451870573684573,-0.06614632159471512,0.05164307728409767,-0.05465538427233696,0.04040970280766487,0.021688034757971764,-1.5303916931152344,0.1526644378900528,0.024382734671235085],[-0.030100017786026,-0.2461627721786499,0.04945126175880432,-0.2677895128726959,-0.07733625918626785,0.13172397017478943,0.05016104876995087,0.07110205292701721,0.009407483972609043,0.06681864708662033,0.1328272521495819,-0.15475091338157654,0.1460334062576294,-0.06688442081212997,0.09932690113782883,0.2040305733680725,0.022517738863825798,0.13617466390132904,0.04821336641907692,-0.09033911675214767,-0.5744708776473999,0.01996513456106186,-0.10498637706041336,-0.19794070720672607],[-0.5047187805175781,0.10445021092891693,0.026053063571453094,0.21554453670978546,-0.1255190670490265,-0.051993418484926224,0.017090441659092903,0.039097860455513,-0.054485730826854706,0.2215459793806076,0.09269285202026367,0.06201014667749405,0.10694754123687744,-0.042138565331697464,0.15799297392368317,-0.09723929315805435,-0.0497150681912899,-0.12715131044387817,0.11602281779050827,0.03763512149453163,0.39959079027175903,0.482621967792511,0.17697946727275848,-0.07549850642681122],[0.1553586721420288,-0.006302502006292343,0.05880922079086304,0.11283580213785172,-0.0256279818713665,-0.18786826729774475,0.0626089870929718,0.10995734483003616,0.03817317262291908,0.041810542345047,-0.023454822599887848,0.04468546807765961,0.031067151576280594,-0.12033142894506454,-0.008605335839092731,0.047381456941366196,0.13168132305145264,0.15517225861549377,0.17691384255886078,-0.05351966992020607,-0.4472716152667999,0.38912147283554077,-0.23484817147254944,0.08016667515039444],[0.06011465564370155,0.16590113937854767,-0.09296244382858276,0.05314871668815613,0.06280746310949326,0.05274536460638046,0.08570756018161774,0.0660303607583046,0.01635146699845791,-0.024964744225144386,0.05591278895735741,0.08146928995847702,0.08431220799684525,-0.12682192027568817,-0.013375332579016685,-0.08925727009773254,0.23219451308250427,0.14529314637184143,0.0068380204029381275,-0.3929031193256378,-0.3222366273403168,0.6531752943992615,0.03553488478064537,0.1716422140598297],[0.45006436109542847,-0.15222316980361938,0.00786069966852665,0.6208692193031311,-0.11042577773332596,0.27721479535102844,0.033313628286123276,-0.028791774064302444,-0.12139550596475601,0.0026972051709890366,0.015112633816897869,-0.04160939157009125,-0.04523294046521187,-0.04495083913207054,-0.0705619603395462,-0.04527346044778824,-0.09199225902557373,-0.018814435228705406,-0.08399642258882523,-0.05700090155005455,0.2712039351463318,-0.9986604452133179,0.013744855299592018,0.032362256199121475],[-0.035227980464696884,0.16634267568588257,-0.05178604647517204,0.25408896803855896,-0.18697072565555573,-0.031116807833313942,0.059639979153871536,0.030917545780539513,-0.1661439687013626,0.06378674507141113,0.04915454611182213,0.1429981142282486,-0.09779086709022522,-0.03112426958978176,-0.019406119361519814,-0.061391182243824005,-0.009123094379901886,0.008619412779808044,-0.0852711945772171,0.1020125076174736,0.12292598932981491,-0.36247965693473816,0.24098128080368042,0.03613517805933952],[0.3600251078605652,0.0015331576578319073,-0.08029503375291824,0.07544278353452682,-0.01157124899327755,0.2266504168510437,0.10029414296150208,0.09208120405673981,0.05856530740857124,0.015521286055445671,-0.09827657788991928,-0.07239961624145508,0.039314739406108856,-0.0506797656416893,-0.06025426462292671,0.014952309429645538,-0.056879397481679916,-0.11255785077810287,-0.21556352078914642,-0.15098699927330017,-0.0019549070857465267,0.6557639241218567,0.17027798295021057,0.016252553090453148],[-0.5185861587524414,0.19312652945518494,0.10047715157270432,0.21404530107975006,-0.09963053464889526,-0.249593585729599,-0.028621815145015717,-0.04143540933728218,0.07609879225492477,-0.05768478661775589,-0.012133046053349972,-0.020230842754244804,-0.1006259098649025,0.05155498906970024,0.03806804120540619,0.01603369601070881,-0.12640494108200073,-0.05386761575937271,0.2631063759326935,0.02594858594238758,-0.13517357409000397,-0.30972781777381897,-0.3078286945819855,-0.024190034717321396],[-0.5413722395896912,-0.013958167284727097,-0.08173458278179169,0.10949098318815231,0.1864003986120224,-0.28200653195381165,0.024935787543654442,0.023524802178144455,0.029246538877487183,0.010632392019033432,-0.009833886288106441,-0.03206825256347656,0.08210903406143188,0.02546100690960884,-0.027495425194501877,0.06692089885473251,-0.14243756234645844,-0.09309398382902145,0.433022677898407,0.07791420817375183,-0.3862462639808655,-0.6431077122688293,-0.33005908131599426,-0.025505010038614273],[-0.24343307316303253,-0.03784357011318207,0.04278205335140228,0.06520276516675949,-0.27868780493736267,-0.25741076469421387,0.13461333513259888,0.06866142898797989,-0.011127554811537266,0.06719740480184555,0.1285153031349182,-0.03575903922319412,-0.003457095008343458,0.016070514917373657,-0.09910362958908081,-0.02503226324915886,-0.022939587011933327,0.028234144672751427,0.05013330653309822,0.15050558745861053,0.5661672353744507,0.040401995182037354,0.5407315492630005,-0.038571570068597794],[-0.07250955700874329,-0.052934326231479645,0.04699462652206421,0.29008719325065613,-0.0010964858811348677,0.22301140427589417,-0.015999196097254753,0.05088037997484207,0.047259971499443054,-0.04768895357847214,-0.07170871645212173,-0.06335002183914185,-0.05169548839330673,0.0360494926571846,-0.11072474718093872,0.09489557147026062,-0.1048952266573906,-0.12390230596065521,0.10510815680027008,-0.14699514210224152,-0.24640411138534546,0.8322039842605591,-0.5146347284317017,0.04405529797077179],[-0.43582770228385925,-0.13404372334480286,0.038388848304748535,-0.15573842823505402,-0.10600774735212326,-0.13021981716156006,0.02727687917649746,-0.06559144705533981,-0.08226791769266129,0.10027757287025452,0.08239724487066269,-0.026441236957907677,0.1184285506606102,0.009689266793429852,0.010841768234968185,4.134803748456761e-05,-0.10750354826450348,-0.10440972447395325,-0.03802395612001419,0.3873212933540344,-0.2887248694896698,-0.5098633766174316,0.017373962327837944,-0.046006400138139725],[-0.5134639143943787,-0.058737970888614655,-0.041602298617362976,-0.16211290657520294,0.10292300581932068,-0.2479708045721054,-0.11066951602697372,-0.14034685492515564,-0.07922590523958206,-0.053024835884571075,-0.0038165776059031487,-0.054820746183395386,0.048610869795084,-0.01860622502863407,-0.05261709541082382,0.04953537881374359,-0.0315159372985363,-0.09669326990842819,0.030203359201550484,-0.05522426217794418,-0.1444302350282669,0.925359547138
