=== maargin/yohaku-challenge7/schema/socrates_top.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "socrates_top.json",
  "type": "array",
  "maxItems": 100,
  "items": {
    "type": "object",
    "required": ["id1", "name1", "id2", "name2", "tca", "range_km", "rel_speed_kms", "max_prob"],
    "properties": {
      "id1": {"type": "integer", "minimum": 1},
      "name1": {"type": "string", "maxLength": 64},
      "id2": {"type": "integer", "minimum": 1},
      "name2": {"type": "string", "maxLength": 64},
      "tca": {"type": "string", "pattern": "^\\d{4}-\\d{2}-\\d{2}[ T]\\d{2}:\\d{2}"},
      "range_km": {"type": "number", "minimum": 0},
      "rel_speed_kms": {"type": "number", "minimum": 0},
      "max_prob": {"type": "number", "minimum": 0, "maximum": 1}
    },
    "additionalProperties": false
  }
}

=== maargin/yohaku-challenge7/web/data/socrates_top.json
[{"id1":28220,"id2":68508,"max_prob":1.0,"name1":"SHIYAN-1 (SY-1) [+]","name2":"STARLINK-37262 [+]","range_km":0.003,"rel_speed_kms":11.291,"tca":"2026-09-26 23:40:41.757"},{"id1":100753,"id2":100759,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38399 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-27 22:46:57.574"},{"id1":100753,"id2":100759,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38399 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-27 22:50:18.450"},{"id1":100753,"id2":100759,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38399 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-27 22:55:18.301"},{"id1":100753,"id2":100759,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38399 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 00:16:50.793"},{"id1":100753,"id2":100759,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38399 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 01:46:32.368"},{"id1":100753,"id2":100759,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38399 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 03:16:52.241"},{"id1":100753,"id2":100759,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38399 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 04:46:37.053"},{"id1":100753,"id2":100759,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38399 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 04:50:18.244"},{"id1":100753,"id2":100759,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38399 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 04:55:18.232"},{"id1":100753,"id2":100759,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38399 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 05:00:18.179"},{"id1":100753,"id2":100759,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38399 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 05:05:18.128"},{"id1":100753,"id2":100759,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38399 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 06:15:15.226"},{"id1":100753,"id2":100759,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38399 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 07:46:25.222"},{"id1":100753,"id2":100759,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38399 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 09:16:25.591"},{"id1":100753,"id2":100759,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38399 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 10:46:39.346"},{"id1":100753,"id2":100759,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38399 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 12:16:48.299"},{"id1":100753,"id2":100759,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38399 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 12:20:18.178"},{"id1":100753,"id2":100760,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38383 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-27 22:46:57.574"},{"id1":100753,"id2":100760,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38383 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-27 22:50:18.450"},{"id1":100753,"id2":100760,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38383 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-27 22:55:18.301"},{"id1":100753,"id2":100760,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38383 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 00:16:50.793"},{"id1":100753,"id2":100760,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38383 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 01:46:32.368"},{"id1":100753,"id2":100760,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38383 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 03:16:52.241"},{"id1":100753,"id2":100760,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38383 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 04:46:37.053"},{"id1":100753,"id2":100760,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38383 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 04:50:18.244"},{"id1":100753,"id2":100760,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38383 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 04:55:18.232"},{"id1":100753,"id2":100760,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38383 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 05:00:18.179"},{"id1":100753,"id2":100760,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38383 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 05:05:18.128"},{"id1":100753,"id2":100760,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38383 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 06:15:15.226"},{"id1":100753,"id2":100760,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38383 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 07:46:25.222"},{"id1":100753,"id2":100760,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38383 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 09:16:25.591"},{"id1":100753,"id2":100760,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38383 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 10:46:39.346"},{"id1":100753,"id2":100760,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38383 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 12:16:48.299"},{"id1":100753,"id2":100760,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38383 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 12:20:18.178"},{"id1":100753,"id2":100761,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38402 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-27 22:46:57.574"},{"id1":100753,"id2":100761,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38402 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-27 22:50:18.450"},{"id1":100753,"id2":100761,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38402 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-27 22:55:18.301"},{"id1":100753,"id2":100761,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38402 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 00:16:50.793"},{"id1":100753,"id2":100761,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38402 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 01:46:32.368"},{"id1":100753,"id2":100761,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38402 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 03:16:52.241"},{"id1":100753,"id2":100761,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38402 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 04:46:37.053"},{"id1":100753,"id2":100761,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38402 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 04:50:18.244"},{"id1":100753,"id2":100761,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38402 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 04:55:18.232"},{"id1":100753,"id2":100761,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38402 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 05:00:18.179"},{"id1":100753,"id2":100761,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38402 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 05:05:18.128"},{"id1":100753,"id2":100761,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38402 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 06:15:15.226"},{"id1":100753,"id2":100761,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38402 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 07:46:25.222"},{"id1":100753,"id2":100761,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38402 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 09:16:25.591"},{"id1":100753,"id2":100761,"max_prob":1.0,"name1":"STARLINK-38381 [+]","name2":"STARLINK-38402 [+]","range_km":0.003,"rel_speed_kms":0.0,"tca":"2026-09-28 10:46:39.346"}]
